-- ==========================================
-- SCRIPT DE CONFIGURACIÓN DE BASE DE DATOS (SUPABASE)
-- Barbería WAVE - Panel de Administración Seguro (Opción B)
-- Copiar y pegar este código completo en el SQL Editor de Supabase y ejecutarlo.
-- ==========================================

-- 1. Crear las tablas principales si no existen
CREATE TABLE IF NOT EXISTS public.services (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    duration INTEGER NOT NULL DEFAULT 30,
    price NUMERIC NOT NULL,
    description TEXT,
    icon TEXT,
    is_active BOOLEAN NOT NULL DEFAULT true,
    order_index INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS public.day_availability (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    friday BOOLEAN NOT NULL DEFAULT true,
    saturday BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS public.custom_time_ranges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    day TEXT NOT NULL CHECK (day IN ('friday', 'saturday')),
    start TEXT NOT NULL, -- HH:mm
    "end" TEXT NOT NULL,  -- HH:mm
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS public.appointments (
    id TEXT PRIMARY KEY,
    customer_name TEXT NOT NULL,
    customer_phone TEXT NOT NULL,
    customer_email TEXT,
    service_name TEXT NOT NULL,
    service_price NUMERIC NOT NULL,
    service_duration INTEGER NOT NULL,
    service_icon TEXT NOT NULL,
    date TEXT NOT NULL,
    time TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'confirmed' CHECK (status IN ('confirmed', 'completed', 'cancelled', 'no-show')),
    notes TEXT,
    ip_address TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    deleted_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS public.banned_ips (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ip_address TEXT NOT NULL UNIQUE,
    reason TEXT,
    banned_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS public.banned_phones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone TEXT NOT NULL UNIQUE,
    reason TEXT,
    banned_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS public.banned_emails (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    reason TEXT,
    banned_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- ==========================================
-- 2. HABILITAR ROW LEVEL SECURITY (RLS)
-- ==========================================
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.day_availability ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.custom_time_ranges ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.banned_ips ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.banned_phones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.banned_emails ENABLE ROW LEVEL SECURITY;

-- ==========================================
-- 3. CREAR POLÍTICAS DE ROW LEVEL SECURITY (RLS)
-- ==========================================

-- Limpiar políticas previas por si se vuelve a ejecutar
DROP POLICY IF EXISTS "Servicios legibles por cualquiera" ON public.services;
DROP POLICY IF EXISTS "Servicios modificables solo por admin" ON public.services;
DROP POLICY IF EXISTS "Disponibilidad legible por cualquiera" ON public.day_availability;
DROP POLICY IF EXISTS "Disponibilidad modificable solo por admin" ON public.day_availability;
DROP POLICY IF EXISTS "Rangos legibles por cualquiera" ON public.custom_time_ranges;
DROP POLICY IF EXISTS "Rangos modificables solo por admin" ON public.custom_time_ranges;
DROP POLICY IF EXISTS "Baneos IPs accesibles solo por admin" ON public.banned_ips;
DROP POLICY IF EXISTS "Baneos Teléfonos accesibles solo por admin" ON public.banned_phones;
DROP POLICY IF EXISTS "Baneos Emails accesibles solo por admin" ON public.banned_emails;
DROP POLICY IF EXISTS "Turnos legibles por cualquiera" ON public.appointments;
DROP POLICY IF EXISTS "Turnos insertables por cualquiera" ON public.appointments;
DROP POLICY IF EXISTS "Turnos actualizables por cualquiera" ON public.appointments;
DROP POLICY IF EXISTS "Turnos administración total" ON public.appointments;

-- Políticas de lectura libre para configuración, modificaciones reservadas para Administrador Autenticado
CREATE POLICY "Servicios legibles por cualquiera" ON public.services FOR SELECT USING (true);
CREATE POLICY "Servicios modificables solo por admin" ON public.services FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Disponibilidad legible por cualquiera" ON public.day_availability FOR SELECT USING (true);
CREATE POLICY "Disponibilidad modificable solo por admin" ON public.day_availability FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Rangos legibles por cualquiera" ON public.custom_time_ranges FOR SELECT USING (true);
CREATE POLICY "Rangos modificables solo por admin" ON public.custom_time_ranges FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Tablas de baneos (Lectura/Edición restringida exclusivamente a Administrador Autenticado)
CREATE POLICY "Baneos IPs accesibles solo por admin" ON public.banned_ips FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Baneos Teléfonos accesibles solo por admin" ON public.banned_phones FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Baneos Emails accesibles solo por admin" ON public.banned_emails FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Tabla de Turnos (Appointments)
-- Lectura: Habilitar SELECT general (filtrado luego por permisos de columna a nivel de rol anon)
CREATE POLICY "Turnos legibles por cualquiera" ON public.appointments FOR SELECT USING (true);
-- Inserción: Permitir a cualquiera crear turnos (reservas)
CREATE POLICY "Turnos insertables por cualquiera" ON public.appointments FOR INSERT WITH CHECK (true);
-- Actualización: Permitir a cualquiera actualizar turnos (para marcar deleted_at al cancelar)
CREATE POLICY "Turnos actualizables por cualquiera" ON public.appointments FOR UPDATE USING (true) WITH CHECK (true);
-- Administrador autenticado tiene acceso total (INSERT, SELECT, UPDATE, DELETE)
CREATE POLICY "Turnos administración total" ON public.appointments FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- ==========================================
-- 4. SEGURIDAD A NIVEL DE COLUMNAS (COLUMN LEVEL SECURITY)
-- ==========================================

-- Revocar todos los accesos en la tabla appointments para el rol público (anon)
REVOKE ALL ON public.appointments FROM anon;

-- Conceder al rol anon la lectura exclusivamente de columnas no sensibles
GRANT SELECT (
    id, service_name, service_price, service_duration, service_icon, 
    date, time, status, created_at, updated_at, deleted_at
) ON public.appointments TO anon;

-- Conceder al rol anon la posibilidad de insertar todos los datos de su propio turno
GRANT INSERT (
    id, customer_name, customer_phone, customer_email, 
    service_name, service_price, service_duration, service_icon, 
    date, time, status, notes, ip_address
) ON public.appointments TO anon;

-- Conceder al rol anon la posibilidad de actualizar únicamente la cancelación del turno
GRANT UPDATE (
    deleted_at, updated_at
) ON public.appointments TO anon;

-- Asegurar que el Administrador Autenticado tenga todos los privilegios sobre todas las columnas
GRANT ALL ON public.appointments TO authenticated;

-- ==========================================
-- 5. TRIGGER DE BASE DE DATOS PARA ENFORZAR BANEOS (SEGURIDAD SERVIDOR)
-- ==========================================
CREATE OR REPLACE FUNCTION public.check_appointment_bans()
RETURNS TRIGGER AS $$
DECLARE
    ip_exists BOOLEAN;
    phone_exists BOOLEAN;
    email_exists BOOLEAN;
    ban_reason TEXT;
BEGIN
    -- Validar IP
    IF NEW.ip_address IS NOT NULL THEN
        SELECT EXISTS(SELECT 1 FROM public.banned_ips WHERE ip_address = NEW.ip_address), reason
        INTO ip_exists, ban_reason
        FROM public.banned_ips WHERE ip_address = NEW.ip_address LIMIT 1;
        
        IF ip_exists THEN
            RAISE EXCEPTION '🚫 Tu IP ha sido bloqueada. No puedes crear turnos.%', COALESCE(' Razón: ' || ban_reason, '');
        END IF;
    END IF;

    -- Validar Teléfono (normalizando espacios, guiones y paréntesis)
    SELECT EXISTS(
        SELECT 1 FROM public.banned_phones 
        WHERE regexp_replace(phone, '\s|-|\(|\)', '', 'g') = regexp_replace(NEW.customer_phone, '\s|-|\(|\)', '', 'g')
    ), reason
    INTO phone_exists, ban_reason
    FROM public.banned_phones 
    WHERE regexp_replace(phone, '\s|-|\(|\)', '', 'g') = regexp_replace(NEW.customer_phone, '\s|-|\(|\)', '', 'g') LIMIT 1;

    IF phone_exists THEN
        RAISE EXCEPTION '🚫 Este teléfono ha sido bloqueado. No puedes crear turnos.%', COALESCE(' Razón: ' || ban_reason, '');
    END IF;

    -- Validar Email
    IF NEW.customer_email IS NOT NULL AND NEW.customer_email <> '' THEN
        SELECT EXISTS(SELECT 1 FROM public.banned_emails WHERE LOWER(email) = LOWER(NEW.customer_email)), reason
        INTO email_exists, ban_reason
        FROM public.banned_emails WHERE LOWER(email) = LOWER(NEW.customer_email) LIMIT 1;

        IF email_exists THEN
            RAISE EXCEPTION '🚫 Este email ha sido bloqueado. No puedes crear turnos.%', COALESCE(' Razón: ' || ban_reason, '');
        END IF;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Asociar el trigger a la tabla
DROP TRIGGER IF EXISTS enforce_appointment_bans ON public.appointments;
CREATE TRIGGER enforce_appointment_bans
BEFORE INSERT ON public.appointments
FOR EACH ROW
EXECUTE FUNCTION public.check_appointment_bans();
